# Generated by Django 4.2 on 2024-05-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediaSite', '0005_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
