# Generated by Django 4.2 on 2024-05-17 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MediaSite', '0006_alter_status_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='user',
        ),
        migrations.AddField(
            model_name='shift',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
